name: ci

on:
  # Trigger this workflow on push events to the main branch.
  push:
    branches:
      - main
  # Trigger this workflow on pull request events to the main branch.
  pull_request:
    branches:
      - main
  # Run this workflow manually from the Actions tab.
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to checkout the source repository.
permissions:
  contents: read

# Set the default Python version for jobs.
env:
  DEFAULT_PYTHON_VERSION: '3.10'

jobs:
  # Run code checks.
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
          cache: poetry
      - name: Install dependencies
        run: make install
      - name: Check with black
        run: make check-black
      - name: Check with isort
        run: make check-isort
      - name: Check with codespell
        run: make check-codespell

  # Run the test suite.
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test
