name: test

on:
  push:
    paths:
      - '.github/workflows/test.yaml'
      - 'pydra/**'
      - 'tests/**'
  pull_request:
    paths:
      - '.github/workflows/test.yaml'
      - 'pydra/**'
      - 'tests/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Hatch
        run: pipx install hatch
      - name: Lint codebase
        run: hatch run lint:all

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: pipx install hatch
      - name: Test codebase
        run: hatch run +python=${{ matrix.python-version }} test:cov
