name: test

on:
  # Trigger this workflow on push events to the main branch.
  push:
    branches:
      - main
  # Trigger this workflow on pull request events to the main branch.
  pull_request:
    branches:
      - main
  # Run this workflow manually from the Actions tab.
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to checkout the source repository.
permissions:
  contents: read

jobs:
  # Lint codebase.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Hatch
        run: pipx install hatch
      - name: Lint codebase
        run: hatch run lint:all

  # Test codebase.
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Hatch
        run: pipx install hatch
      - name: Test codebase
        run: hatch run +python=${{ matrix.python-version }} test:cov
